### ISSUE TITLE
Try not to create duplicate indexes

### ISSUE THREAD

**Issue by dwillis** [TheUpshot/Bedfellows#1]

**Comment by nikeiubel** [comment]
I did notice this issue when I first added indexes. Because this is an
issue only with the three input tables fec_candidates, fec_committees,
fec_committee_contributions (since the others are already dropped first and
then recreated) and this really only becomes a problem if you recompute the
scores several times on the same database, I thought all the extra code to
check whether an index already exists wouldn't be worth it. But I'm happy
to fix this issue.

**Comment by dwillis** [comment]
I've got it for now, but my solution isn't particularly elegant: if the index already exists or the script tries to drop one that doesn't exist, those specific errors are ignored.
